"""
Corrected JD .docx builder — template reconstruction, NOT LLM rewriting.
Uses only verified fields; zero new LLM call; cannot hallucinate (§8.3).
"""
from io import BytesIO
from typing import Any

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def build_corrected_jd(record: dict[str, Any]) -> bytes:
    doc = Document()

    # ── Header ───────────────────────────────────────────────────────────────
    title = doc.add_heading(record.get("role", "Job Description"), 0)
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT

    level_line = doc.add_paragraph()
    level_run = level_line.add_run(f"Level: {record.get('ai_seniority', 'Unknown')}")
    level_run.bold = True

    # Verified badge
    if record.get("is_verified"):
        v_run = level_line.add_run("  [VERIFIED]")
        v_run.bold = True
        v_run.font.color.rgb = RGBColor(0x16, 0xA3, 0x4A)  # green
    else:
        v_run = level_line.add_run("  [UNVERIFIED — level defaulted to Uncertain]")
        v_run.font.color.rgb = RGBColor(0xDC, 0x26, 0x26)  # red

    doc.add_paragraph()

    # ── Summary (indicative) ─────────────────────────────────────────────────
    doc.add_heading("Summary (Indicative — AI Generated)", level=2)
    s_para = doc.add_paragraph(record.get("one_line_summary", ""))
    s_para.runs[0].italic = True
    note = doc.add_paragraph()
    note_run = note.add_run("Note: This summary is AI-generated and not verified against source text.")
    note_run.font.size = Pt(9)
    note_run.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    doc.add_paragraph()

    # ── Skills ───────────────────────────────────────────────────────────────
    doc.add_heading("Required Skills (Traced from Text)", level=2)
    skills = record.get("required_skills", [])
    if skills:
        skill_para = doc.add_paragraph(", ".join(s.title() for s in skills))
    else:
        doc.add_paragraph("No hard skills explicitly identified in the source text.")

    doc.add_paragraph()

    # ── Grounding quote ───────────────────────────────────────────────────────
    if record.get("is_verified"):
        doc.add_heading("Seniority Evidence (Verified Quote)", level=2)
        q_para = doc.add_paragraph(f'"{record.get("raw_text_justification", "")}"')
        q_para.runs[0].italic = True

    doc.add_paragraph()

    # ── Corrections / Flags ──────────────────────────────────────────────────
    flags = []
    if record.get("audit_mismatch"):
        native = record.get("native_label", "stated level")
        ai = record.get("ai_seniority", "extracted level")
        flags.append(
            f"LEVEL MISMATCH: Stated/implied title suggests '{native}' but text signals '{ai}' — "
            f"review before posting."
        )
    bias = record.get("bias_flags", [])
    if bias:
        flags.append(f"LANGUAGE FLAGGED FOR REVIEW: {', '.join(bias)}")
    if not record.get("pay_range_present"):
        flags.append(
            "NO PAY RANGE: Adding compensation info improves candidate conversion "
            "(India trend: 50%+ postings now include pay — Indeed India 2025)."
        )

    if flags:
        doc.add_heading("Corrections & Flags", level=2)
        for flag in flags:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(flag)

    doc.add_paragraph()

    # ── Quality score ─────────────────────────────────────────────────────────
    doc.add_heading("Quality Score", level=2)
    score = record.get("quality_score", 0)
    breakdown = record.get("score_breakdown", [])
    doc.add_paragraph(f"{score}/100  ({' · '.join(breakdown) if breakdown else 'no breakdown'})")
    doc.add_paragraph("This is a relative completeness score, not an absolute grade.")

    # ── Footer ────────────────────────────────────────────────────────────────
    doc.add_paragraph()
    footer_para = doc.add_paragraph()
    footer_run = footer_para.add_run(
        "Generated by TalentSync · Indicative summary not verified · "
        "Seniority tied to exact source quote above."
    )
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(0x9C, 0xA3, 0xAF)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
